### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Delimer** [ecoron/ImagicalMine-php7-linux#1]
./bin/php7/bin/php: error while loading shared libraries: /home/user/bin/php7/bin/../lib/libz.so.1: file too short

**Comment by ecoron** [comment]
ok seems it's a missing dep or something, but try

https://github.com/ImagicalMine/ImagicalMine/blob/php7-0.14/compile-php7.sh

to compile the php7 bin, maybe this helps you.

**Comment by Delimer** [comment]
Thanks, I compile php7 and its work fine!
